# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
default:
  tags:
  - kubernetes-farpoint-default
image: golang:latest
stages:
- test
- build
- deploy
- release
format:
  stage: test
  script:
  - go fmt $(go list ./... | grep -v /vendor/)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -race $(go list ./... | grep -v /vendor/)
compile:
  stage: build
  variables:
    KUBERNETES_CPU_REQUEST: 4
    KUBERNETES_CPU_LIMIT: 6
    KUBERNETES_MEMORY_REQUEST: 12Gi
    KUBERNETES_MEMORY_LIMIT: 16Gi
  script:
  - go install github.com/mitchellh/gox@latest
  - mkdir -p bin
  - $GOPATH/bin/gox --parallel=4 --osarch=!darwin/386 --output="bin/{{.Dir}}_{{.OS}}_{{.Arch}}"
  - $GOPATH/bin/gox --parallel=4 --osarch=darwin/arm64 --output="bin/{{.Dir}}_{{.OS}}_{{.Arch}}"
  artifacts:
    paths:
    - bin
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
  - if: "$CI_COMMIT_TAG"
  script:
  - echo "Creating new release"
  release:
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
      - name: Linux-x86
        url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/raw/bin/$CI_PROJECT_NAME_linux_386?job=compile
        link_type: package
      - name: Linux-x64
        url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/raw/bin/$CI_PROJECT_NAME_linux_amd64?job=compile
        link_type: package
      - name: Windows-x86
        url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/raw/bin/$CI_PROJECT_NAME_windows_386.exe?job=compile
        link_type: package
      - name: Windows-x64
        url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/raw/bin/$CI_PROJECT_NAME_windows_amd64.exe?job=compile
        link_type: package
      - name: Darwin-amd64
        url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/raw/bin/$CI_PROJECT_NAME_darwin_amd64?job=compile
        link_type: package
      - name: Darwin-arm64
        url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/raw/bin/$CI_PROJECT_NAME_darwin_arm64?job=compile
        link_type: package
include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
sast:
  stage: test
